[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
tad_contracts = "G9bxnJromWRrVNNP4WgY4u2x2E7tWJ317vjEaKxpqbJb"

[programs.localnet]
tad_contracts = "G9bxnJromWRrVNNP4WgY4u2x2E7tWJ317vjEaKxpqbJb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/volkovivan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899
